var React = require('react');
var ReactRouter = require('react-router');

var Detail = React.createClass({

getInitialState: function(){
  return {
  }
},
componentDidMount: function() {
},
render: function(){
  var boxStyle = { float: "left", width: "200px", height: "50%",
    padding: "10px 20px 20px 10px", margin: "180px 0px 10px 20px", backgroundColor: "Transparent", color: "white"
  };
  var featuredStyle = {
    color: "#F1C232",
    fontSize: "30px"
  };
  return <div style={boxStyle}>
        <h4 style={{color: "#F1C232", fontSize: "30px"}}> FEATURED </h4>
        <h4 style={{fontSize: "20px"}}> Quad-Copter </h4>
        <h4 style={{fontSize: "12px"}}> Multirotor helicopter that is lifted and propelled by four rotors.
        Their life is generated by a set of rotors. </h4>
        <button style={{borderColor:"white", backgroundColor: "Transparent", color:"white", padding: "10px 20px 10px 20px"}}> See Project </button>
   </div>
}
});

module.exports = Detail;
